require("lazy-config")
require("settings")
require("keymappings")
require("autopairs-config")
require("lualine-config")
-- require("colorschemes-config.onedark")
require("colorschemes-config.gruvbox")
require("nvim-tree-config")
require("comment-nvim-config")
require("colorizer-config")
require("indent-blankline-config")
require("telescope-config")
require("treesitter-config")
require("lsp-config.mason")
require("lsp-config.lspsaga")
require("lsp-config.completion")
require("noice-config")
